# This is a basic workflow to help you get started with Actions

name: workday

# Controls when the workflow will run
on:
  schedule: 
  - cron: '* * * * *'
  # - cron: '50 0 * * 1,2,3,4,5' 


jobs:
  workday: 
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run start
